apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservicedeployment
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      name: userservicepod
      labels:
        app: userservice
    spec:
      containers:
        - name: userservicecontainer
          image: rpantax/user-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: userservicesvc
spec:
  type: LoadBalancer
  selector:
    app: userservice
  ports:
    - port: 80
      targetPort: 8080