server:
  port: 8082

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://mysql-users:3306/db_users
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    hostname: user-service
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always
